### ISSUE TITLE
Do not append trailing slash for static resources

### ISSUE THREAD

**Issue by OleksandrRakovets** [fsasvari/laravel-trailing-slash#28]
Hi Frano! Cheers for the great package, it's a pleasure to work with complete urls :)

Is there any elegant solution to omit trailing slash for images and other files ending with `.xxx` or `.xxxx`?

At the moment I have to trim it in controllers and would like to configure in one place.

**Comment by fsasvari** [comment]
Thank you, Oleksandr :)

It's on the features list, but don't know when I will have more time on implementing that, maybe will have more time around Christmas holidays, we'll see. Basically, it's some kind of implementation for including/excluding urls from configuration file. If anything pops out, will let you know ;)

**Comment by OleksandrRakovets** [comment]
Actually I have found the `asset()` helper which does not seem to be affected by the package, so I'll stick to it for files.

**Comment by fsasvari** [comment]
Great! I will close the issue then. If something else occurs just post the issue here again ;)
