### ISSUE TITLE
Missing app.asset_url configuration

### ISSUE THREAD

**Issue by michaloravec** [fsasvari/laravel-trailing-slash#29]
Hi,

In RoutingServiceProvider in method registerUrlGenerator() is missing app.asset_url which allow asset root urls to be configurable
https://github.com/laravel/framework/commit/9172a67b783952c1d3e15452d9c8646dc0b3eb6d

There is screen from laravel:
![image](https://user-images.githubusercontent.com/22096293/70500044-dc755c80-1b1a-11ea-9fe2-b30c844ddcfa.png)

So this part https://github.com/fsasvari/laravel-trailing-slash/blob/master/src/RoutingServiceProvider.php#L34

should be:

            $url = new UrlGenerator(
                $routes, $app->rebinding(
                    'request', $this->requestRebinder()
                ), $app->make('config')->get('app.asset_url');
            );

Could you add this to your package?

**Comment by fsasvari** [comment]
Thanks Michal for reporting the potential problem. I am on it, hopefully will update the package this week and bump it to a newer version.

**Comment by fsasvari** [comment]
Fixed in v1.1.0, thanks for reporting!
