### ISSUE TITLE
Support POST requests

### ISSUE THREAD

**Issue by aik099** [fsasvari/laravel-trailing-slash#3]
Currently, when POST request is made without trailing `/` then redirect (in `.htaccess`) that adds it transforms POST request into GET request.

Following solution from https://stackoverflow.com/questions/17295085/redirection-on-apache-maintain-post-params I recommend 

* replacing `RewriteRule (.*) %{REQUEST_URI}/ [R=301,L]`
* with `RewriteRule (.*) %{REQUEST_URI}/ [R=301,P,L]` (added `,P`)

The `P` doesn't mean POST, but proxy and if `mod_proxy` is installed on Apache it does preserve POST request method.

**Comment by aik099** [comment]
On the second thought I was trying to apply changes to `.htaccess` without registering service provider provided here. So may not be a bug after all.

And strangely this `,P` addition resulted in some random malfunction, where redirect to url with `/` were not made.

**Comment by fsasvari** [comment]
Please make some testings and report back if problem occurs, thanks.

**Comment by aik099** [comment]
Actually better to leave it as is, because not all Apache versions even support POST redirects.
