### ISSUE TITLE
Allow Laravel 7?

### ISSUE THREAD

**Issue by OleksandrRakovets** [fsasvari/laravel-trailing-slash#30]
I have tested the package on Laravel 7 project and it did not cause any issues. At the same time [the diff of `illuminate/routing`](https://github.com/illuminate/routing/compare/6.x...7.x) looks significant and I don't understand its internals yet. So I'm hesitant to submit a basic PR for `package.json` only.

Could you please take a look if it's good to allow v7?

**Comment by fsasvari** [comment]
Hi there! Of course, it's on the todo list, will look into it this weekend. Was waiting for Laravel v7 to be more stable etc.

Yeah, I see a lot of changes in Routing logic from v6 to v7 so I need to test everything out.

Stay tuned, will let you know about the progress 😉

**Comment by fsasvari** [comment]
And it's done! Fewer changes that I thought  😄
