### ISSUE TITLE
Trailing slash didn't work on heroku

### ISSUE THREAD

**Issue by refojunior** [fsasvari/laravel-trailing-slash#34]
I have laravel application on heroku, I want to add trailing slash on the URL using this package, but nothing works. 
Heroku automatically redirecting and remove the trailing slash, can you help me with this? I was struggled and tried everything to make it for days

**Comment by fsasvari** [comment]
Hi there! Does Heroku have some kind of admin panel where you can set up things like redirects etc?

The package works fine under apache2, nginx, local set up, production server, tested on a couple of projects...

**Comment by refojunior** [comment]
sorry for my bad, the issue is from my htaccess that automatically remove the trailing slash, 
Thank you very much
