### ISSUE TITLE
Laravel 9 Compatibility

### ISSUE THREAD

**Issue by silverhand7** [fsasvari/laravel-trailing-slash#38]
Please update this package to support the latest version of the Laravel framework.

**Comment by silverhand7** [comment]
https://github.com/fsasvari/laravel-trailing-slash/pull/39

**Comment by silverhand7** [comment]
Review this PR for Laravel 9 compatibility 
https://github.com/fsasvari/laravel-trailing-slash/pull/39

**Comment by michaloravec** [comment]
Why is always only with this package?

**Comment by fsasvari** [comment]
Sorry for taking some time on this, merged & done!
