### ISSUE TITLE
Paginator fix (question)

### ISSUE THREAD

**Issue by clecocqith** [fsasvari/laravel-trailing-slash#42]
Hi,

What is the bug with the paginator actually? It seems to work by my side.
Is it because it's adding a / before /?page=2? or it was fixed?

Thanks :)

**Comment by fsasvari** [comment]
Can you give me some example code? Paginator should work as well, there were no bugs reported, yet... :)

**Comment by fsasvari** [comment]
@xorenir is not fixed yet, don't know if it's possible, but there is a workaround:

```
$users = User::paginate()->withQueryString();
$users->setPath(URL::current());
```

And on the blade view:
```
{{ $users->links() }}
```

**Comment by xorenir** [comment]
@fsasvari thank u.
