### ISSUE TITLE
Problems with livewire

### ISSUE THREAD

**Issue by clecocqith** [fsasvari/laravel-trailing-slash#43]
Hi again,

Does your package work with livewire? Do you have some project running with livewire and your package?

I have some strange behaviors on livewire and I dont know if it's related to the package.

Thanks in advance.

**Comment by clecocqith** [comment]
Ok I think there is a problem with livewire because the route for ajax requested changed: http://preprod.orizzonte.test/livewire/message/search to http://preprod.orizzonte.test/livewire/message/search/

**Comment by fsasvari** [comment]
Thanks for the input, closing the ticket as its livewire thing :)
