### ISSUE TITLE
needed laravel 10 support

### ISSUE THREAD

**Issue by furiousjayed** [fsasvari/laravel-trailing-slash#44]

**Comment by skyjebus** [comment]
👋🏻 

Any plans to support laravel 10 in the future?

**Comment by fsasvari** [comment]
Yes, ofc, sorry for waiting... Ill try to finish it this week or beginning of the next one :)

**Comment by fsasvari** [comment]
Done! https://github.com/fsasvari/laravel-trailing-slash/tree/v5.0.0
