### ISSUE TITLE
Trailing slash not applied to paginate/pagination links

### ISSUE THREAD

**Issue by bridgeport** [fsasvari/laravel-trailing-slash#6]
First, thanks for this package. It looks like the trailing slash isn't being applied to pagination links.

Also, the `previousPageUrl()` and `nextPageUrl()` pagination methods don't add the trailing slash. I am those two particular function functions to build prev and next links, as such:

```html
<link rel="prev" href="https://example.test/widgets?page=1">
<link rel="next" href="https://example.test/widgets?page=3">
```

Thanks.

**Comment by fsasvari** [comment]
Thank for reporting a problem, will look into it as soon as possible.

**Comment by fsasvari** [comment]
I tried, but with no success.

There is a huge problem with overriding Laravel's `Paginator` and `LengthAwarePaginator` classes. There are no contracts provided, and no way to change default `pagination` classes in `ServiceProviders`.

So, every time you use `paginate()` method on your models, query builders etc., you must set current path for pagination links. Example:

```php
$texts = Text::where('is_active', 1)->paginate();
$texts->setPath(URL::current());

$texts->links();
```
