### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by MichalOravec** [fsasvari/laravel-trailing-slash#8]
And what about [optional parameters](https://laravel.com/docs/5.6/routing#parameters-optional-parameters)?

Adding trailing slash to route with optional parameters is problem.

**Comment by fsasvari** [comment]
Hi, thanks for reporting a problem, will look into it this week ;)

One question: what function or class/method do you use to generate URL with optional parameters ?

**Comment by MichalOravec** [comment]
Hi, when i use later, it was working very good. So you dont need look.

**Comment by fsasvari** [comment]
OK, glad to hear :)
