### ISSUE TITLE
Update for Laravel 5.7

### ISSUE THREAD

**Issue by DevDavido** [fsasvari/laravel-trailing-slash#9]
Please make this package Laravel 5.7 compatible as it keeps composer from updating to 5.7.
There was a [change to the Routing part](https://laravel.com/docs/5.7/upgrade) of the framework, but it seems only the Route::redirect method returns a 302 HTTP status code redirect now.

**Comment by fsasvari** [comment]
Hi, sorry for not replying sooner, been busy lately. Thanks for pull request, will check and merge this weekend ;)

**Comment by DevDavido** [comment]
Any updates? 😃

**Comment by fsasvari** [comment]
Sorry, nothing yet :( will look into it this weekend, I promise ;)

**Comment by bridgeport** [comment]
@fsasvari Thanks for looking into this. This is the one package that I'm waiting for in order to complete my upgrade to Laravel 5.7.

**Comment by fsasvari** [comment]
Needed to create a new branch, it is available now at https://github.com/fsasvari/laravel-trailing-slash/tree/0.3
